create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list w_clk_in_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 28 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {led_inst[1]/q_cnt[0]} {led_inst[1]/q_cnt[1]} {led_inst[1]/q_cnt[2]} {led_inst[1]/q_cnt[3]} {led_inst[1]/q_cnt[4]} {led_inst[1]/q_cnt[5]} {led_inst[1]/q_cnt[6]} {led_inst[1]/q_cnt[7]} {led_inst[1]/q_cnt[8]} {led_inst[1]/q_cnt[9]} {led_inst[1]/q_cnt[10]} {led_inst[1]/q_cnt[11]} {led_inst[1]/q_cnt[12]} {led_inst[1]/q_cnt[13]} {led_inst[1]/q_cnt[14]} {led_inst[1]/q_cnt[15]} {led_inst[1]/q_cnt[16]} {led_inst[1]/q_cnt[17]} {led_inst[1]/q_cnt[18]} {led_inst[1]/q_cnt[19]} {led_inst[1]/q_cnt[20]} {led_inst[1]/q_cnt[21]} {led_inst[1]/q_cnt[22]} {led_inst[1]/q_cnt[23]} {led_inst[1]/q_cnt[24]} {led_inst[1]/q_cnt[25]} {led_inst[1]/q_cnt[26]} {led_inst[1]/q_cnt[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 28 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {led_inst[0]/q_cnt[0]} {led_inst[0]/q_cnt[1]} {led_inst[0]/q_cnt[2]} {led_inst[0]/q_cnt[3]} {led_inst[0]/q_cnt[4]} {led_inst[0]/q_cnt[5]} {led_inst[0]/q_cnt[6]} {led_inst[0]/q_cnt[7]} {led_inst[0]/q_cnt[8]} {led_inst[0]/q_cnt[9]} {led_inst[0]/q_cnt[10]} {led_inst[0]/q_cnt[11]} {led_inst[0]/q_cnt[12]} {led_inst[0]/q_cnt[13]} {led_inst[0]/q_cnt[14]} {led_inst[0]/q_cnt[15]} {led_inst[0]/q_cnt[16]} {led_inst[0]/q_cnt[17]} {led_inst[0]/q_cnt[18]} {led_inst[0]/q_cnt[19]} {led_inst[0]/q_cnt[20]} {led_inst[0]/q_cnt[21]} {led_inst[0]/q_cnt[22]} {led_inst[0]/q_cnt[23]} {led_inst[0]/q_cnt[24]} {led_inst[0]/q_cnt[25]} {led_inst[0]/q_cnt[26]} {led_inst[0]/q_cnt[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {led_inst[0]/q_led}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {led_inst[1]/q_led}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {led_inst[0]/q_rst}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {led_inst[1]/q_rst}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets w_clk_in_BUFG]
